### ISSUE TITLE
await on an unitialized  futures (future in a field) leads to NullPointerException

### ISSUE THREAD

**Issue by rudi** [abstools/abstools#102]
---

Author Name: **Nikolaos Bezirgiannis** (Nikolaos Bezirgiannis)
Original Redmine Issue: 189, https://envisage.ifi.uio.no:8080/redmine/issues/189
Original Date: 2015-07-16

---

Maybe I reported this bug again because I have seen this error before when awaiting on an uninitialized future:

java.lang.NullPointerException
	at abs.backend.java.lib.runtime.ABSFutureGuard.isTrue(ABSFutureGuard.java:21)
	at abs.backend.java.lib.runtime.ABSRuntime.await(ABSRuntime.java:344)
	at NullFut.C_c.start(C_c.java:77)
	at NullFut.Main$1.execute(Main.java:34)
	at abs.backend.java.lib.runtime.Task.run(Task.java:190)
	at abs.backend.java.scheduling.DefaultTaskScheduler$SchedulerThread.run(DefaultTaskScheduler.java:82)
Error in abs.backend.java.lib.runtime.ABSRuntime```6f45ee7f:
Sorry, this is a bug in the Java backend of ABS: Unexpected exception: java.lang.NullPointerException

I attach the offending program.

**Comment by rudi** [comment]
Attached file:
```
module NullFut;

interface I {
    Unit resolve();
    Unit start();
}

class C implements I {
    Fut<Unit> f;
    Unit start() { await f?; }
    Unit resolve() { f = this ! dummy(); }
    Unit dummy() { }
}

{
    I o = new C();
    o ! start();
    o ! resolve();
}
```

**Comment by rudi** [comment]
I'd argue this is a case of undefined or erroneous behavior.  We don't delay sending messages to uninitialized variables of the correct type, instead, we crash with a NullPointerException.  For me, the case with futures is analogous.

Leaving open for now since we might want to document this case.
