### ISSUE TITLE
ABS frontend cannot build with latest Apache Ant version

### ISSUE THREAD

**Issue by rudi** [abstools/abstools#14]
---

Author Name: **Nikolaos Bezirgiannis** (Nikolaos Bezirgiannis)
Original Redmine Issue: 81, https://envisage.ifi.uio.no:8080/redmine/issues/81
Original Date: 2013-11-08

---

System: Archlinux 64bit
Java: Tested both on Java 6 and Java 7
Ant version: Test both on 1.9.2 and 1.9.0

Running ant under frontend/ fails with:

Buildfile: /home/bezirg/Dropbox/Repos/abs/frontend/build.xml

prepare:

genshell:

genflex:
     [echo] Running jflex

BUILD FAILED
/home/bezirg/Dropbox/Repos/abs/frontend/build.xml:235: java.lang.NoSuchMethodError: java_cup.runtime.lr_parser.getSymbolFactory()Ljava_cup/runtime/SymbolFactory;
        at JFlex.CUP$LexParse$actions.CUP$LexParse$do_action(LexParse.java:1703)
        at JFlex.LexParse.do_action(LexParse.java:408)
        at java_cup.runtime.lr_parser.parse(lr_parser.java:569)
        at JFlex.Main.generate(Main.java:73)
        at JFlex.anttask.JFlexTask.execute(JFlexTask.java:71)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
        at org.apache.tools.ant.Main.runBuild(Main.java:851)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

Total time: 0 seconds

The build is though successful with Ant 1.8.4.

**Comment by rudi** [comment]
---

Original Redmine Comment
Author Name: **Volker Stolz** (Volker Stolz)
Original Date: 2013-11-14T11:00:27Z

---

Can't reproduce on MacOS with 1.9.2:

```
ifibrilator:frontend vs$ ~/Downloads/apache-ant-1.9.2/bin/ant 
Buildfile: /Users/vs/git/abstools/frontend/build.xml

prepare:

genshell:
     [copy] Copying 1 file to /Users/vs/git/abstools/frontend/bin/bash

genflex:
     [echo] Running jflex

genast:
  [jastadd] generating node types and weaving aspects

```

**Comment by rudi** [comment]
---

Original Redmine Comment
Author Name: **Nikolaos Bezirgiannis** (Nikolaos Bezirgiannis)
Original Date: 2013-11-21T12:10:34Z

---

Volker Stolz wrote:
> Can't reproduce on MacOS with 1.9.2:
> 
> [...]

You were right. 
It was the fault of compiling in Dropbox. For some reason you cannot use the latest Ant (1.9.0 and 1.9.2) with Dropbox.
I should pass this over to the Ant development team.
