### ISSUE TITLE
Compiler crash when using traits, related to module system

### ISSUE THREAD

**Issue by rm2340** [abstools/abstools#163]
This code:
```
module A;
trait T = {}
module B;
trait T = {}
```
makes the compiler crash:
```
java.util.NoSuchElementException
	at java.util.LinkedList.removeFirst(LinkedList.java:270)
```

**Comment by VolkerStolz** [comment]
A little bit more context:
```
java.util.NoSuchElementException
	at java.util.LinkedList.removeFirst(LinkedList.java:270)
	at java.util.LinkedList.pop(LinkedList.java:801)
	at abs.frontend.ast.Model.applyTraits(Model.java:583)
```
