### ISSUE TITLE
Runtime error in Eclipse

### ISSUE THREAD

**Issue by rudi** [abstools/abstools#18]
---

Author Name: **Volker Stolz** (Volker Stolz)
Original Redmine Issue: 86, https://envisage.ifi.uio.no:8080/redmine/issues/86
Original Date: 2013-11-13
Original Assignee: Volker Stolz

---

There's another runtime error hidden in the Eclipse plugin. It doesn't seem to have any serious effect, though.

```
java.lang.RuntimeException: Circular definition of attr: getDecl in class: org.jastadd.ast.AST.SynDecl
	at abs.frontend.ast.VarUse.getDecl(VarUse.java:353)
	at abs.frontend.ast.VarUse.rewriteTo(VarUse.java:375)
	at abs.frontend.ast.ASTNode.getChild(ASTNode.java:606)
	at abs.frontend.ast.ASTNode.collect_contributors_Stmt_getAACs(ASTNode.java:1098)
	at abs.frontend.ast.ASTNode.collect_contributors_Stmt_getAACs(ASTNode.java:1098)
	at abs.frontend.ast.ASTNode.collect_contributors_Stmt_getAACs(ASTNode.java:1098)
	at abs.frontend.ast.ASTNode.collect_contributors_Stmt_getAACs(ASTNode.java:1098)
	at abs.frontend.ast.Stmt.collect_contributors_Stmt_getAACs(Stmt.java:351)
	at abs.frontend.ast.Stmt.getAACs_compute(Stmt.java:618)
	at abs.frontend.ast.Stmt.getAACs(Stmt.java:587)
	at abs.frontend.ast.Stmt.rewriteTo(Stmt.java:529)
	at abs.frontend.ast.VarDeclStmt.rewriteTo(VarDeclStmt.java:578)
	at abs.frontend.ast.ASTNode.getChild(ASTNode.java:606)
	at abs.frontend.ast.List.getNumChild(List.java:208)
	at abs.frontend.ast.Block.getStmtList(Block.java:601)
	at abs.frontend.ast.Block.getStmt(Block.java:558)
	at abs.frontend.ast.Block.Define_VarOrFieldDecl_lookupVarOrFieldName(Block.java:790)
	at abs.frontend.ast.ASTNode.Define_VarOrFieldDecl_lookupVarOrFieldName(ASTNode.java:1683)
	at abs.frontend.ast.ASTNode.Define_VarOrFieldDecl_lookupVarOrFieldName(ASTNode.java:1683)
	at abs.frontend.ast.ASTNode.Define_VarOrFieldDecl_lookupVarOrFieldName(ASTNode.java:1683)
	at abs.frontend.ast.ASTNode.Define_VarOrFieldDecl_lookupVarOrFieldName(ASTNode.java:1683)
	at abs.frontend.ast.ASTNode.Define_VarOrFieldDecl_lookupVarOrFieldName(ASTNode.java:1683)
	at abs.frontend.ast.Exp.lookupVarOrFieldName(Exp.java:415)
	at abs.frontend.ast.VarUse.getDecl_compute(VarUse.java:370)
	at abs.frontend.ast.VarUse.getDecl(VarUse.java:358)
	at org.absmodels.abs.plugin.editor.ABSCodeScanner.evalAST(ABSCodeScanner.java:321)
	at org.absmodels.abs.plugin.editor.ABSCodeScanner.internalNextToken(ABSCodeScanner.java:259)
	at org.absmodels.abs.plugin.editor.ABSCodeScanner.nextToken(ABSCodeScanner.java:230)
	at org.eclipse.jface.text.rules.DefaultDamagerRepairer.createPresentation(DefaultDamagerRepairer.java:175)

```

**Comment by rudi** [comment]
---

Original Redmine Comment
Author Name: **Volker Stolz** (Volker Stolz)
Original Date: 2013-11-26T16:16:26Z

---

The underlying problem is probably that the ABSCodeScanner violates the contract established by the grammar:
A CompilationUnit *must* have a parent Model, because it uses inherent attributes.

```
java.lang.RuntimeException: Trying to evaluate attribute in subtree not attached to main tree
	at abs.frontend.ast.CompilationUnit.lookupModule(CompilationUnit.java:1298)
	at abs.frontend.ast.CompilationUnit.Define_ModuleDecl_lookupModule(CompilationUnit.java:1354)
	at abs.frontend.ast.ASTNode.Define_ModuleDecl_lookupModule(ASTNode.java:1662)
	at abs.frontend.ast.ModuleDecl.lookupModule(ModuleDecl.java:1515)
	at abs.frontend.typechecker.TypeCheckerHelper.getImportedNames(TypeCheckerHelper.java:279)
	at abs.frontend.ast.ModuleDecl.getImportedNames_compute(ModuleDecl.java:1280)
	at abs.frontend.ast.ModuleDecl.getImportedNames(ModuleDecl.java:1267)
	at abs.frontend.typechecker.TypeCheckerHelper.getVisibleNames(TypeCheckerHelper.java:310)
	at abs.frontend.ast.ModuleDecl.getVisibleNames_compute(ModuleDecl.java:1088)
	at abs.frontend.ast.ModuleDecl.getVisibleNames(ModuleDecl.java:1075)
	at abs.frontend.ast.ModuleDecl.resolveName(ModuleDecl.java:385)
	at abs.frontend.ast.ModuleDecl.lookup_compute(ModuleDecl.java:1494)
	at abs.frontend.ast.ModuleDecl.lookup(ModuleDecl.java:1481)
	at abs.frontend.ast.ModuleDecl.Define_Decl_lookup(ModuleDecl.java:1604)
	at abs.frontend.ast.ASTNode.Define_Decl_lookup(ASTNode.java:1669)
	at abs.frontend.ast.ASTNode.Define_Decl_lookup(ASTNode.java:1669)
	at abs.frontend.ast.ASTNode.Define_Decl_lookup(ASTNode.java:1669)
	at abs.frontend.ast.ASTNode.Define_Decl_lookup(ASTNode.java:1669)
	at abs.frontend.ast.DataTypeUse.lookup(DataTypeUse.java:401)
	at abs.frontend.ast.ParametricDataTypeUse.Define_Decl_lookup(ParametricDataTypeUse.java:550)
	at abs.frontend.ast.ASTNode.Define_Decl_lookup(ASTNode.java:1669)
	at abs.frontend.ast.Exp.lookup(Exp.java:438)
	at abs.frontend.ast.TypeUse.getDecl_compute(TypeUse.java:393)
	at abs.frontend.ast.TypeUse.getDecl(TypeUse.java:381)
	at abs.frontend.ast.UnresolvedTypeUse.rewriteTo(UnresolvedTypeUse.java:365)
	at abs.frontend.ast.ASTNode.getChild(ASTNode.java:606)
	at abs.frontend.ast.List.rewriteTo(List.java:287)
	at abs.frontend.ast.ASTNode.getChild(ASTNode.java:606)
	at abs.frontend.parser.SourcePosition.findPosition(SourcePosition.java:43)

```

**Comment by rudi** [comment]
---

Original Redmine Comment
Author Name: **Volker Stolz** (Volker Stolz)
Original Date: 2013-11-26T16:57:05Z

---

Fix in place, let's see how it holds up.
