### ISSUE TITLE
my first attempt for ABS

### ISSUE THREAD

**Issue by Yasqader** [abstools/abstools#317]
hello everyone,

my first attempt at ABS is a code exactly same as account sample that we have in documentation.  but an error accrued. anybody can help me on this error?

The editor is Emacs on Ubuntu OS.

![Screenshot from 2023-01-26 08-20-44](https://user-images.githubusercontent.com/116618344/214762478-3b128dd7-fcd0-4b99-87c8-de9a68f1e891.png)
![Screenshot from 2023-01-26 08-21-44](https://user-images.githubusercontent.com/116618344/214762485-d38a3930-b220-4e02-a385-bc377bcace1c.png)
![Screenshot from 2023-01-26 08-22-04](https://user-images.githubusercontent.com/116618344/214762488-314aefcf-3599-4137-a104-97ec07578809.png)

**Comment by rudi** [comment]
Could you post the file instead of the screenshots, so we can be sure that we try with the same input as you?  Also, could you post the link to the documentation where you found the example you gave?  (This is so we can fix the example if needed.)

But I also see that in your screenshot there's a class definition in the middle of the productline part of the model, and that there does not seem to be module declaration (that's why it is important to post the file, not screenshots).

Modules, which contain classes, functions and data types, have to occur before deltas and producline declarations, and no class can occur outside of a module declaration.  I checked, and this is not documented properly in the language manual.  I filed https://github.com/abstools/abstools/issues/318 to keep track of this documentation problem.

**Comment by Yasqader** [comment]
Based on grammar rule that you sent, I changed the code and the file is enclosed and I found the code here https://abs-models.org/documentation/tutorials/language-tutorial/ from section 8.2 feature description to 8.5 product selection.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Yasqader** [comment]
I checked the code and found that i should add an interface to it so the code is corrected again but a new error accrued,
**absc --java "firstAbsModelingCode.abs" 
An error occurred during compilation:
null).**
how should i resolve this error?
the code file is attached.
[firstAbsModelingCode.zip](https://github.com/abstools/abstools/files/10525313/firstAbsModelingCode.zip)

**Comment by VolkerStolz** [comment]
Some more details:
```
$ frontend/bin/bash/absc checkspl firstAbsModelingCode.abs 
java.lang.NullPointerException: Cannot invoke "org.abs_models.frontend.ast.DeltaDecl.getParam(int)" because "dd" is null
	at org.abs_models.frontend.typechecker.TypeCheckerHelper.typeCheckProductDecl(TypeCheckerHelper.java:238)
	at org.abs_models.frontend.ast.ProductDecl.typeCheck(ProductDecl.java:121)
```
That looks like an unhandled error in the compiler.

**Comment by VolkerStolz** [comment]
@Yasqader You only define two deltas (`DFee, DSave`) so far, and later you use other deltas (`DType`) which don't exist. We need a few more seatbelts in the compiler here to give a better error message, but your model is inconsistent there.

**Comment by VolkerStolz** [comment]
Thank you for your report, I've just pushed slightly improved error-reporting there.
