### ISSUE TITLE
Eclipse runtime error

### ISSUE THREAD

**Issue by rudi** [abstools/abstools#39]
---

Author Name: **Volker Stolz** (Volker Stolz)
Original Redmine Issue: 116, https://envisage.ifi.uio.no:8080/redmine/issues/116
Original Date: 2014-01-24

---

This happened when the editor tripped over a ```case e:{..}``` stmt (note the ```:```).
Again, the question is whether the editor should run rewrite rules or not (#85,#86) -- probably especially not on models that don't parse!

```
Caused by: java.lang.AssertionError: Should never happen for a well-typed model:UnknownType/<UNKNOWN>
	at abs.frontend.typechecker.Type.toUse(Type.java:264)
	at abs.frontend.ast.Stmt.rewriteRule0(Stmt.java:551)
	at abs.frontend.ast.Stmt.rewriteTo(Stmt.java:532)
	at abs.frontend.ast.ExpressionStmt.rewriteTo(ExpressionStmt.java:464)
	at abs.frontend.ast.ASTNode.getChild(ASTNode.java:607)
	at abs.frontend.ast.List.rewriteTo(List.java:288)
	at abs.frontend.ast.ASTNode.getChild(ASTNode.java:607)
	at abs.frontend.ast.Block.getStmtList(Block.java:601)
	at abs.frontend.ast.Block.getNumStmt(Block.java:541)
	at abs.frontend.ast.Block.hasRewriteBlockAt(Block.java:87)
	at abs.frontend.ast.Block.rewriteTo(Block.java:813)
	at abs.frontend.ast.ASTNode.getChild(ASTNode.java:607)
	at abs.frontend.parser.SourcePosition.findPosition(SourcePosition.java:43)
	at abs.frontend.parser.SourcePosition.findPosition(SourcePosition.java:43)
	at abs.frontend.parser.SourcePosition.findPosition(SourcePosition.java:43)
	at abs.frontend.parser.SourcePosition.findPosition(SourcePosition.java:43)
	at abs.frontend.parser.SourcePosition.findPosition(SourcePosition.java:43)
	at abs.frontend.parser.SourcePosition.findPosition(SourcePosition.java:43)
	at abs.frontend.parser.SourcePosition.findPosition(SourcePosition.java:43)
	at abs.frontend.parser.SourcePosition.findPosition(SourcePosition.java:34)
	at org.absmodels.abs.plugin.util.UtilityFunctions.getASTNodeOfOffset(UtilityFunctions.java:373)
	at org.absmodels.abs.plugin.editor.ABSCodeScanner.evalAST(ABSCodeScanner.java:307)
	at org.absmodels.abs.plugin.editor.ABSCodeScanner.internalNextToken(ABSCodeScanner.java:260)
	at org.absmodels.abs.plugin.editor.ABSCodeScanner.nextToken(ABSCodeScanner.java:231)
	at org.eclipse.jface.text.rules.DefaultDamagerRepairer.createPresentation(DefaultDamagerRepairer.java:175)

```

**Comment by rudi** [comment]
---

Original Redmine Comment
Author Name: **Volker Stolz** (Volker Stolz)
Original Date: 2014-02-10T13:01:08Z

---

I think I fixed this with the recent commit to the PatterVar rewrite mechanisms; at least I can't reproduce it anymore.
