### ISSUE TITLE
[eclipse-plugin] PDE fails to load ABS perspective because of `org.abs-models.sdedit`

### ISSUE THREAD

**Issue by nobeh** [abstools/abstools#4]
I am quite sure that I am missing something, but debugging the eclipse-plugin fails to load ABS perspective:

```
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
!SESSION 2015-07-30 21:01:40.087 -----------------------------------------------
eclipse.buildId=4.5.0.I20150603-2000
java.version=1.8.0_60-ea
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.platform.ide
Command-line arguments:  -product org.eclipse.platform.ide -data /nobeh/dev/workspaces/crisp/ws-abstools/../runtime-EclipseApplication -dev file:/nobeh/dev/workspaces/crisp/ws-abstools/.metadata/.plugins/org.eclipse.pde.core/Eclipse Application/dev.properties -os linux -ws gtk -arch x86_64 -consoleLog

!ENTRY org.abs-models.abs.plugin 4 0 2015-07-30 21:01:42.345
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.abs-models.abs.plugin [531]
  Unresolved requirement: Require-Bundle: org.abs-models.sdedit; bundle-version="0.0.0"

    at org.eclipse.osgi.container.Module.start(Module.java:434)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1561)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1476)
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
    at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
```

My environment:
- Java 1.8.0_60
- Eclipse PDE Mars Release

**Comment by VolkerStolz** [comment]
On 30/07/15 21:04, Behrooz Nobakht wrote:
> I am quite sure that I am missing something, but debugging the
> eclipse-plugin fails to load ABS perspective:

Do you have the org.abs-models.sdedit checked out in your workspace as well?

  -V

**Comment by nobeh** [comment]
I think so:

```bash
$ pwd
/nobeh/dev/workspaces/crisp/ws-abstools/abstools/eclipse-plugin
$ ls .. | grep sde
sdedit-for-abs
```

**Comment by nobeh** [comment]
Good hint. I just imported the project `org.abs-models.sdedit` into eclipse and it got fixed.
