### ISSUE TITLE
Deadlock checker crashes on some examples

### ISSUE THREAD

**Issue by rudi** [abstools/abstools#43]
---

Author Name: **Volker Stolz** (Volker Stolz)
Original Redmine Issue: 120, https://envisage.ifi.uio.no:8080/redmine/issues/120
Original Date: 2014-01-28
Original Assignee: Michael Lienhardt

---

According to https://envisage.ifi.uio.no:8080/jenkins/job/ABS-Bucky-Tests/lastCompletedBuild/testReport/, it crashes on some models like:

```
java.lang.AssertionError: Couldn't find class Comparator
	at abs.frontend.ast.Call.typeInference(Call.java:219)
	at abs.frontend.ast.VarDecl.typeInference(VarDecl.java:213)
	at abs.frontend.ast.VarDeclStmt.typeInference(VarDeclStmt.java:210)
	at abs.frontend.ast.Block.typeInference(Block.java:275)
	at abs.frontend.ast.MethodImpl.typeInference(MethodImpl.java:227)
	at abs.frontend.ast.ClassDecl.typeInference(ClassDecl.java:295)
	at abs.frontend.ast.ModuleDecl.typeInference(ModuleDecl.java:340)
	at abs.frontend.ast.CompilationUnit.typeInference(CompilationUnit.java:97)
	at abs.frontend.ast.Model.typeInference(Model.java:389)
	at deadlock.analyser.Analyser.deadlockAnalysis(Analyser.java:52)
	at deadlock.DeadlockCheckerTests.parse(DeadlockCheckerTests.java:27)
	at abs.frontend.parser.ParseSamplesTest.test(ParseSamplesTest.java:54)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)

```

(Not all failures on Jenkins are relevant, though, sometimes the model is buggy)

**Comment by rudi** [comment]
---

Original Redmine Comment
Author Name: **Michael Lienhardt** (Michael Lienhardt)
Original Date: 2014-01-29T14:25:21Z

---

It seems that the error comes from the fact that in SmartHome, there is no class implementing the Observer interface (even if there are method calls done on objects of that interface).

The fact that there can be some implementation missing is something that we didn't consider when we coded the deadlock analysis. 

I added some code (basically considering that non implemented method have a 0 contract and variable return value) that deal with that case.

**Comment by rudi** [comment]
---

Original Redmine Comment
Author Name: **Volker Stolz** (Volker Stolz)
Original Date: 2014-03-11T13:16:17Z

---

As Michael promised, it's back in disguise:
```
java.lang.NullPointerException
	at abs.frontend.ast.Call.typeInference(Call.java:240)
	at abs.frontend.ast.ExpressionStmt.typeInference(ExpressionStmt.java:148)
	at abs.frontend.ast.Block.typeInference(Block.java:275)
	at abs.frontend.ast.WhileStmt.typeInference(WhileStmt.java:169)
	at abs.frontend.ast.Block.typeInference(Block.java:275)
	at abs.frontend.ast.MethodImpl.typeInference(MethodImpl.java:247)
	at abs.frontend.ast.ClassDecl.typeInference(ClassDecl.java:308)
	at abs.frontend.ast.ModuleDecl.typeInference(ModuleDecl.java:347)
	at abs.frontend.ast.CompilationUnit.typeInference(CompilationUnit.java:106)
	at abs.frontend.ast.Model.typeInference(Model.java:369)
	at deadlock.analyser.Analyser.deadlockAnalysis(Analyser.java:52)
	at deadlock.DeadlockCheckerTests.parse(DeadlockCheckerTests.java:28)

```
