### ISSUE TITLE
JUnit: AssertionErros vs. AssumptionViolatedExceptions in descendants of ExamplesTypeChecking

### ISSUE THREAD

**Issue by rudi** [abstools/abstools#61]
---

Author Name: **Volker Stolz** (Volker Stolz)
Original Redmine Issue: 139, https://envisage.ifi.uio.no:8080/redmine/issues/139
Original Date: 2014-03-05

---

Some of the JUnit code which builds on the assumption that the input is fine is still producing `AssertionErrors` instead of `AssumptionViolatedExceptions`. The reason is a jump through a static method instead of somehow using the `onError`-provider from the actual test class.

``````
java.lang.AssertionError: Failed to parse: abs/lang/abslang.abs & examples/chatPL/Chat.abs & examples/chatPL/ChatPL.abs & examples/chatPL/FeatureModel.abs & examples/chatPL/Management.abs & examples/chatPL/Products.abs & examples/chatPL/StateRegToHigh.abs
Parse errors: 3. First error:
Chat.abs```149:Syntactic error: unexpected token IDENTIFIER
    at org.junit.Assert.fail(Assert.java:88)
    at abs.ABSTest.assertParseModelOk(ABSTest.java:150)
    at abs.ABSTest.assertParseFileOk(ABSTest.java:129)
    at abs.frontend.FrontendTest.assertTypeCheckFileOk(FrontendTest.java:57)
    at abs.frontend.typesystem.ExamplesTypeChecking.parse(ExamplesTypeChecking.java:29)
    at abs.frontend.parser.ParseSamplesTest.test(ParseSamplesTest.java:54)
    at abs.backend.abs2haskell.ABS2HaskellExamplesTest.test(ABS2HaskellExamplesTest.java:38)

``````

**Comment by rudi** [comment]
Haven't seen this problem in 2 years, closing.
